<h1 class='titlecountry'>Pêcher en France</h1>
<section class="introcountry">
    <p class="prescountry">Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
    sed diam nonummy nibh euismod tincidunt ut laoreet dolore
    magna aliquam erat volutpat. Ut wisi enim ad minim veniam,
    quis nostrud exerci tation ullamcorper suscipit lobortis nisl
    ut aliquip ex ea commodo consequat. Duis autem vel eum iriure
    dolor in hendrerit in vulputate velit esse molestie consequat,
    vel illum dolore eu feugiat nulla facilisis at vero eros et
    accumsan et iusto odio dignissim qui blandit praesent luptatum
    zzril delenit augue duis dolore te feugait nulla facilisi.
    Nam liber tempor cum soluta nobis eleifend option congue
    nihil imperdiet doming id quod mazim placerat facer possim
    assum. Typi non habent claritatem insitam; est usus legentis
    in iis qui facit eorum claritatem.</p>
    <iframe src="https://www.google.com/maps/d/embed?mid=1PGd5xe4ZxcIyyJoIWGzRfIPuFj3To-D_" class="countrymap"></iframe>
</section>
<section class="countryspots">
    <?php foreach($countryspots as $countryspot): ?>
    <div class="imgspot">
        <a href="show_region.php?name=<?= $countryspot['name'] ?>&country=<?= $countryspot['country'] ?>">
            <img src="img/<?= $countryspot['img1'] ?>"></img>
            <h2><?= $countryspot['name'] ?></h2>
        </a>
    </div>
    <?php endforeach ?>
</section>   