<div class="connexion">
    <h2>Connexion</h2>
    <form method="post">
        <fieldset>
            <legend>Connexion :</legend>
            <div class="input-group">
                <label for="mail">Email :</label>
                <input type="email" name="mail" id="mail">
            </div>
            <div class="input-group">
                <label for="password">Mot de passe :</label>
                <input type="password" name="password" id="password">
            </div>
            <div class="input-group">
                <div class="button">
                    <input type="submit" value="Se connecter" class="valider">
                    <input type="reset" value="Annuler" class="reset">
                </div>
            </div>
        </fieldset>
    </form>
</div>