<h1>Création d'un compte utilisateur</h1>
<p>Créez maintenant votre compte utilisateur et vous pourrez partager vos commentaires, et même proposer des articles de vos propres spots pour qu'ils soient publiés :)</p>
<div class="register">
    <form action="register.php" method="post">
        <fieldset>
            <legend>Identité et coordonnées</legend>
            <div id="register">
                <label for="lastname">Nom</label>
                <input type="text" name="lastname" id="lastname"/>
                <label for="firstname">Prénom</label>
                <input type="text" name="firstname" id="firstname"/>
                <label for="birthdate">Date de naissance</label>
                <input type="date" name="birthdate" id="birthdate"/>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informations d'authentification</legend>
            <label for="mail">E-mail</label>
            <input type="mail" name="mail" id="mail"/>
            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password"/>
        </fieldset>
        <div><button class="validate">Créer compte</button></div>
    </form>
</div>