<h1 class="titlefishes">Les poissons d'eau de mer</h1>
<p class="intro">Pour l'instant j'ai pêché <?= $seafishescount['seafishesnumber'] ?> espèces de poisson en mer, voici leur présentation :</p>
<?php foreach($seafishes as $seafish): ?>
<div class="fishespage">
    <article class="presentation">
        <h2 class="fishname"><?= $seafish['name'] ?></h2>
        <img src="img/<?= $seafish['img'] ?>" class="circle"></img>
        <div class="fishdetail">
            <p><?= $seafish['description'] ?></p>
            <p><?= $seafish['localisation'] ?></p>
        </div>
        <button class="recipebutton" id="<?= $seafish['name'] ?>">Voir une recette avec ce poisson</button>
    </article>
    <article class="recipe hidden" data-index="<?= $seafish['name'] ?>">
        <i class="fas fa-times-circle"></i>
        <img src="img/<?= $seafish['recipe_img'] ?>"></img>
        <h2><?= $seafish['recipe_name'] ?> (<?= $seafish['country'] ?>)</h2>
        <p><?= $seafish['recipe_description'] ?></p>
    </article>
</div>
<?php endforeach ?>
